model_path: meta-llama/Meta-Llama-3-8B-Instruct

LoRA:
  r: 0
  alpha: 128
  dropout: 0.05

forget_loss: grad_ascent
batch_size: 4
gradient_accumulation_steps: 2
num_epochs: 1
lr: 6e-8
save_steps: 300
with_kl: False

save_dir: ../unlearn_models
weight_decay: 0.01