model_path: HuggingFaceH4/zephyr-7b-beta

LoRA:
  r: 0
  alpha: 128
  dropout: 0.05

forget_loss: scrub
batch_size: 4
gradient_accumulation_steps: 2
num_epochs: 3
lr: 5e-7
save_steps: 70
with_kl: False

save_dir: ../unlearn_models/wmdp_scrub
weight_decay: 0.01