model_path: meta-llama/Llama-2-7b-hf

LoRA:
  r: 0
  alpha: 128
  dropout: 0.05

forget_loss: npo
batch_size: 4
gradient_accumulation_steps: 2
num_epochs: 1.5
lr: 1e-6
save_steps: 60
with_kl: True

save_dir: ../unlearn_models/whp_npo_kl
weight_decay: 0.01